#!/bin/bash

# magic from "Coffee" leftwm theme
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# shutdown everything we started, the bg will remain until
# feh or some other theme or the user sets a new one, idgaf
pkill picom
pkill polybar
