#!/bin/bash

# magic stolen from "Coffee" leftwm theme
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPTPATH/down

# boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom -b --config /home/zaduma/.config/picom/picom.conf
fi

# set background with feh if it exists
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

# magic stolen from "Coffee" leftwm theme
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# boot polybar based on the number of monitors found, if polybar exists obv
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar &> /dev/null &
  done <<< "$monitors"
  exit 0
fi
